addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn
cache:
  yarn: true
  directories:
    - node_modules
language: node_js
node_js:
  - "6"
script: yarn test -- --single-run --browsers Nightmare
